#!/usr/bin/env bash

alias sc='source ~/.bashrc'
alias xx='xterm -fg white -bg midnightblue &'

function set_ps(){
local l_for="\[\033[0;32m\]";
local l_back="\[\033[0;00m\]";

local PS_1="$l_for\u@\W\\$ $l_back "
PS1=$PS_1
}

case $TERM in
	xterm*|rxvt|eterm)
		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\007"'
		set_ps;
		;;
	screen)
		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"'
		;;
esac

export PATH="/usr/local/opt/qt/bin:~/.emacs.d/bin:$PATH"
